# .github/workflows/preview.yml
name: Deploy to GitHub Pages

on:
  push:
    paths:
      - "website/**"
      - "packages/standard/src/**" # for schema generation
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Generate Schema
        uses: ./.github/actions/generate-schema-action

      - name: Install dependencies
        run: |
          cd ./website
          yarn install --frozen-lockfile
      - name: Build website
        run: |
          cd ./website
          yarn build-docs

      # Docs: https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          folder: docs
          force: false
          clean: true
          clean-exclude: pr-preview/
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
