# .github/workflows/preview.yml
name: Deploy Website PR previews

on:
  pull_request:
    paths:
      - "website/**"
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          cd ./website
          yarn
          yarn build-docs

      - name: Deploy preview
        uses: TeselaGen/pr-preview-action@85f363dceadc8c8f5fb71997d39476f3bffbb760
        with:
          source-dir: ./docs/
          preview-branch: main
          umbrella-dir: ./docs/pr-preview
          base-url: https://fsml.org
