# .github/workflows/preview.yml
name: Deploy Website PR previews

on:
  pull_request:
    paths:
      - "website/**"
      - "packages/standard/src/**" # for schema generation
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Schema
        uses: ./.github/actions/generate-schema-action
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        env:
          pr: ${{ github.event.number }}
        run: |
          cd ./website
          yarn
          DOCUSAURUS_PATH_PREFIX="/pr-preview/pr-$pr/" yarn build-docs

      - name: Deploy preview
        uses: ./.github/actions/pr-preview-action
        with:
          source-dir: ./docs/
          preview-branch: gh-pages
          umbrella-dir: ./pr-preview
          base-url: fsml.org
          umbrella-url: pr-preview
