# .github/workflows/preview.yml
name: Deploy Website PR previews

on:
  pull_request:
    paths:
      - "website/**"
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        env:
          umbrellaurl: ${{ inputs.umbrella-url }}
          pr: ${{ github.event.number }}
        run: |
          cd ./website
          yarn
          GATSBY_PATH_PREFIX="$umbrellaurl/pr-$pr" yarn build-docs-pr

      - name: Deploy preview
        uses: ./.github/actions/pr-preview-action
        with:
          source-dir: ./docs/
          preview-branch: main
          umbrella-dir: ./docs/pr-preview
          base-url: fsml.org
          umbrella-url: pr-preview
